version: "3.8"

services:
    # custom image
    php-edi-srv-app:
        container_name: php-edi-srv-app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - user=jenkins
                - uid=114
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - /mnt/edi_diageo:/var/www/storage/edi_diageo
        restart: unless-stopped
        networks:
            - php-edi-srv
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # nginx
    php-edi-srv-nginx:
        container_name: php-edi-srv-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8075:80"
        volumes:
            - ./docker-compose/nginx/:/etc/nginx/conf.d/
            - ./:/var/www
        networks:
            - php-edi-srv

networks:
    php-edi-srv:
        name: php-edi-srv

volumes:
    mariadb-data:
